name: Deploy Ludo Academy
on:
  push:
    branches:
      - main
    paths:
      - 'ludo-academy/**'
      - 'firebase.json'
      - 'firestore.indexes.json'
      - 'package.json'
      - 'package-lock.json'

jobs:
  deploy_academy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only firestore:rules,hosting:ludoacademy
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
