name: Deploy Ludo Academy
on:
  push:
    branches:
      - main
    paths:
      - 'ludo-academy/**'
      - 'firebase.json'
      - '.firebaserc'
jobs:
  deploy_academy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:ludoacademy --project ludoleaguesa-33371
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
